//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtchetS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueComputersInCabinets
    {
        public string Number_cabinet { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
    }
}
