//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtchetS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        public int ID { get; set; }
        public int InventNomer { get; set; }
        public string Name { get; set; }
        public int Kabinet { get; set; }
        public string Monitor { get; set; }
        public string RAM { get; set; }
        public string CPU { get; set; }
        public string Motherboard { get; set; }
        public string MemoryStorage { get; set; }
        public string VideoCard { get; set; }
        public bool AtWork { get; set; }
        public string infoRam { get; set; }
        public string infoCPU { get; set; }
        public string infoMBoard { get; set; }
        public string infoMemory { get; set; }
        public string infoVCard { get; set; }
    
        public virtual Kabinets Kabinets { get; set; }
    }
}
